//signup constants
export const REQUEST_SIGNUP_LOADING = "REQUEST_SIGNUP_LOADING"
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS"
export const REQUEST_SIGNUP_FAILURE = "REQUEST_SIGNUP_FAILURE"


//login constants
export const REQUEST_LOGIN_LOADING = "REQUEST_LOGIN_LOADING"
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS"
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE"
