//signup constants
export const REQUEST_SIGNUP_LOADING = "REQUEST_SIGNUP_LOADING"
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS"
export const REQUEST_SIGNUP_FAILURE = "REQUEST_SIGNUP_FAILURE"


//login constants
export const REQUEST_LOGIN_LOADING = "REQUEST_LOGIN_LOADING"
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS"
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE"


//forgot password
export const REQUEST_FORGOTPASSWORD_LOADING = 'REQUEST_FORGOTPASSWORD_LOADING';
export const REQUEST_FORGOTPASSWORD_SUCCESS = 'REQUEST_FORGOTPASSWORD_SUCCESS';
export const REQUEST_FORGOTPASSWORD_FAILURE = 'REQUEST_FORGOTPASSWORD_FAILURE';

//reset password
export const REQUEST_RESETPASSWORD_LOADING = 'REQUEST_RESETPASSWORD_LOADING';
export const REQUEST_RESETPASSWORD_SUCCESS = 'REQUEST_RESETPASSWORD_SUCCESS';
export const REQUEST_RESETPASSWORD_FAILURE = 'REQUEST_RESETPASSWORD_FAILURE';


//delete user account
export const REQUEST_DELETEACCOUNT_LOADING = 'REQUEST_DELETEACCOUNT_LOADING';
export const REQUEST_DELETEACCOUNT_SUCCESS = 'REQUEST_DELETEACCOUNT_SUCCESS';
export const REQUEST_DELETEACCOUNT_FAILURE = 'REQUEST_DELETEACCOUNT_FAILURE';


